# Generated by Django 3.1.1 on 2020-09-08 16:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VulnerabilityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=64, unique=True)),
                ('publish_date', models.DateField()),
                ('update_date', models.DateField()),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('access_complexity', models.CharField(choices=[('low', 'LOW'), ('medium', 'MEDIUM'), ('high', 'HIGH')], help_text='How much knowledge or skill is required to exploit this vulnerabilty.', max_length=64)),
                ('confidentiality_impact', models.CharField(choices=[('None', 'NONE'), ('Partial', 'PARTIAL'), ('Complete', 'COMPLETE')], help_text='The degree of information disclosure, caused by this vulnerability.', max_length=64)),
                ('integrity_impact', models.CharField(choices=[('None', 'NONE'), ('Partial', 'PARTIAL'), ('Complete', 'COMPLETE')], help_text='How compromise the system is, due to this vulnerability.', max_length=64)),
                ('availability_impact', models.CharField(choices=[('None', 'NONE'), ('Partial', 'PARTIAL'), ('Complete', 'COMPLETE')], help_text='The level of impact on resource availability, caused by this vulnerability.', max_length=64)),
                ('authentication_required', models.BooleanField()),
                ('vulnerability_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vulnerabilities', to='core.vulnerabilitytype')),
            ],
        ),
    ]
