# Generated by Django 3.1.1 on 2020-09-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_field_vulnerability_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilitytype',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
