# Generated by Django 3.1.1 on 2020-09-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_field_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerability',
            name='access_complexity',
            field=models.CharField(choices=[('Low', 'LOW'), ('Medium', 'MEDIUM'), ('High', 'HIGH')], help_text='How much knowledge or skill is required to exploit this vulnerabilty.', max_length=64),
        ),
    ]
